In [1]:
import os

print("Current Working Directory:")
print(os.getcwd())

Current Working Directory:
C:\Users\saksh\Desktop\country-economic-stress-analysis\notebooks

In [2]:
import os

for item in os.listdir():
    print(item)

.ipynb_checkpoints
01_data_understanding.ipynb

In [3]:
import os

os.chdir("..")

print(os.getcwd())

C:\Users\saksh\Desktop\country-economic-stress-analysis

In [4]:
import os

raw_data_path = "data/"

print(os.listdir(raw_data_path))

['country_metadata.csv', 'country_year_indicators.csv', 'economic_stress_score.csv', 'indicator_dictionary.csv']

# Country-Level Economic Stress Monitoring and Predictive Analytics System

## Data Understanding & Data Quality Assessment

### Prepared By
Sakshi Nandgude

### Project Objective
To analyze global economic stress patterns using macroeconomic and food security indicators and identify key drivers of economic vulnerability across countries and regions.

### Dataset
Global Geo-Economic Stress Indicators

### Notebook Purpose

This notebook focuses on:
- Data Loading
- Data Understanding
- Data Quality Assessment
- Data Profiling

In [7]:
# =====================================================
# IMPORT LIBRARIES
# =====================================================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

# Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [8]:
# =====================================================
# LOAD MAIN DATASET
# =====================================================

country_year = pd.read_csv("data/country_year_indicators.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [9]:
# =====================================================
# DATASET SHAPE
# =====================================================

print("Rows:", country_year.shape[0])
print("Columns:", country_year.shape[1])

country_year.shape

Rows: 14322
Columns: 18

(14322, 18)

In [10]:
# =====================================================
# FIRST LOOK AT DATA
# =====================================================

country_year.head()

,country_code,country_name,iso3,region,income_group,year,gdp_growth,inflation,unemployment,gdp_per_capita,population,food_production_index,cereal_yield,cereal_production_tonnes,agricultural_land_pct,dietary_energy_supply_adequacy,economic_stress_score,data_completeness_score
0,ABW,Aruba,ABW,Latin America & Caribbean,High income,1960,NaN,NaN,NaN,NaN,54922.0,NaN,NaN,NaN,NaN,NaN,NaN,0
1,ABW,Aruba,ABW,Latin America & Caribbean,High income,1961,NaN,NaN,NaN,NaN,55578.0,NaN,NaN,NaN,11.1111,NaN,NaN,0
2,ABW,Aruba,ABW,Latin America & Caribbean,High income,1962,NaN,NaN,NaN,NaN,56320.0,NaN,NaN,NaN,11.1111,NaN,NaN,0
3,ABW,Aruba,ABW,Latin America & Caribbean,High income,1963,NaN,NaN,NaN,NaN,57002.0,NaN,NaN,NaN,11.1111,NaN,NaN,0
4,ABW,Aruba,ABW,Latin America & Caribbean,High income,1964,NaN,NaN,NaN,NaN,57619.0,NaN,NaN,NaN,11.1111,NaN,NaN,0

In [11]:
# =====================================================
# COLUMN LIST
# =====================================================

country_year.columns.tolist()

['country_code',
 'country_name',
 'iso3',
 'region',
 'income_group',
 'year',
 'gdp_growth',
 'inflation',
 'unemployment',
 'gdp_per_capita',
 'population',
 'food_production_index',
 'cereal_yield',
 'cereal_production_tonnes',
 'agricultural_land_pct',
 'dietary_energy_supply_adequacy',
 'economic_stress_score',
 'data_completeness_score']

In [12]:
# =====================================================
# DATASET STRUCTURE
# =====================================================

country_year.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14322 entries, 0 to 14321
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country_code                    14322 non-null  object
 1   country_name                    14322 non-null  object
 2   iso3                            14322 non-null  object
 3   region                          14322 non-null  object
 4   income_group                    14322 non-null  object
 5   year                            14322 non-null  int64
 6   gdp_growth                      11214 non-null  float64
 7   inflation                       8971 non-null   float64
 8   unemployment                    6531 non-null   float64
 9   gdp_per_capita                  11569 non-null  float64
 10  population                      14075 non-null  float64
 11  food_production_index           11011 non-null  float64
 12  cereal_yield                    10330 non-null  float64
 13  cereal_production_tonnes        10380 non-null  float64
 14  agricultural_land_pct           12060 non-null  float64
 15  dietary_energy_supply_adequacy  3831 non-null   float64
 16  economic_stress_score           12762 non-null  float64
 17  data_completeness_score         14322 non-null  int64
dtypes: float64(11), int64(2), object(5)
memory usage: 2.0+ MB

In [13]:
# =====================================================
# UNIQUE VALUES IN CATEGORICAL COLUMNS
# =====================================================

categorical_cols = [
    'country_code',
    'country_name',
    'iso3',
    'region',
    'income_group'
]

for col in categorical_cols:
    print(f"\n{col}")
    print("-" * 40)
    print("Unique Values:", country_year[col].nunique())

country_code
----------------------------------------
Unique Values: 217

country_name
----------------------------------------
Unique Values: 217

iso3
----------------------------------------
Unique Values: 217

region
----------------------------------------
Unique Values: 7

income_group
----------------------------------------
Unique Values: 5

In [14]:
# =====================================================
# YEAR COVERAGE
# =====================================================

print("Minimum Year:", country_year['year'].min())
print("Maximum Year:", country_year['year'].max())

print("\nTotal Years:",
      country_year['year'].nunique())

Minimum Year: 1960
Maximum Year: 2025

Total Years: 66

In [15]:
# =====================================================
# DATASET SUMMARY
# =====================================================

summary = pd.DataFrame({
    "Rows": [country_year.shape[0]],
    "Columns": [country_year.shape[1]],
    "Countries": [country_year['country_name'].nunique()],
    "Regions": [country_year['region'].nunique()],
    "Income Groups": [country_year['income_group'].nunique()],
    "Year Start": [country_year['year'].min()],
    "Year End": [country_year['year'].max()]
})

summary

    Rows  Columns  Countries  Regions  Income Groups  Year Start  Year End
0  14322       18        217        7              5        1960      2025